[package]
name = "tinyui"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[lib]
name="tinyui"
crate-type = ["rlib"]

[target.'cfg(macos)'.dependencies]
objc = "0.2"
cocoa = "0.9.2"

[target.'cfg(windows)'.dependencies]
